Fix target submission metadata to support flexible content from ACF
Smartling/wordpress-localization-plugin pull request #250
Opened 2020-09-24 13:23 UTC by vsolovei-smartling

2020-09-24 18:23 UTC, dimitrystd requested changes

2020-09-24 18:23 UTC, dimitrystd commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +                $metaFields = $this->restoreAcfMetaFields($metaFields, $sourceFields['meta']);
I think the line above must copy ALL meta fields, including transient.
It seems you implemented a workaround: if transient field was translated then you restore its value from the source. But it's not right approach. We should prevent modification of transient and other non-translatable fields by our connector.

2020-09-24 18:23 UTC, dimitrystd commented on inc/Smartling/Helpers/XmlEncoder.php
>      public static function xmlDecode($content, SubmissionEntity $submission)
I don't know why "decode" was in "encoder" class before, but it was a single method before. Now we have 3 methods related to decode. Let's reorginize code: move these methods to a new class or rename the current one.

2020-09-25 11:45 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/XmlEncoder.php
>      public static function xmlDecode($content, SubmissionEntity $submission)
Renamed class

2020-09-25 11:46 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +            $this->acfCopyRules = $acfDynamicSupport->getCopyRules();
It could get called multiple times if downloading in bulk

2020-09-25 11:46 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +    private function restoreAcfMetaFields(array $metaFields, array $sourceMetaFields)
Moved

2020-09-25 11:46 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +                if (!array_key_exists('meta', $sourceFields)) {
Done

2020-09-25 11:46 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +        $translation = [];
Done

2020-09-29 03:52 UTC, dimitrystd reviewed
It looks good. I still worry what we plan to release but it's better then before. In general I don't like ACF smell in core classes.

2020-09-29 03:52 UTC, dimitrystd commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +        if (!is_array($source['meta'])) {
It looks very similar to what was before. But with new code if `$source['meta']` was string\int before then you just replace the value with an empty array. It looks ok, just wanted to draw your attention.

2020-09-29 03:52 UTC, dimitrystd commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +            $xmlFields = [];
This name is not clear when you see its usage 50 lines below. Let's call it more specific like `$sorcePostMetaFields` (your name is welcome). And initialize it with `meta` of the original post. If someone will need other source fields then I prefer to push him to update the code and fix tests rather than just add usage of this variable in one more place.

2020-09-29 03:52 UTC, dimitrystd commented on inc/Smartling/Helpers/FieldsFilterHelper.php
> +        if ($strategy === self::FILTER_STRATEGY_UPLOAD && !GlobalSettingsManager::isAcfDisabled()) {
Just want to confirm that we don't have other hooks before calling this method. I prefer to keep ACF logic aside from core fields handling. We may anticipate more such plugins and it will be not sexy to put all of their code here.

2020-09-29 03:52 UTC, dimitrystd commented on inc/Smartling/Helpers/XmlHelper.php
> +    public function xmlDecode($content, SubmissionEntity $submission)
Did you remove `static` for testing?

2020-09-29 03:52 UTC, dimitrystd commented on readme.txt
> +* New behaviour of Auto synchronize properties on translated page with source expert profile setting. When turned on, extends support of ACF flexible fields in metadata.
Added more details. Mostly for us when we will review what and when was added.
```
* Major change in `Auto synchronize properties` behavior. Starting from this release connector always replace all metadata in a translated post with metadata from the source post. Then connector applies translations to freshly copied metadata.
* If you use ACF flexible fields then you should enable `Auto synchronize properties`. It will force connector always replicate ACF fields from source to target and keep flexible fields consistent
```

2020-09-29 07:31 UTC, PavelLoparev requested changes
Have no additional comments. Let's fix what @dimitrystd mentioned and release it

2020-09-29 11:38 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/FieldsFilterHelper.php
> +        if ($strategy === self::FILTER_STRATEGY_UPLOAD && !GlobalSettingsManager::isAcfDisabled()) {
This is the beginning of work with content

2020-09-29 11:38 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/XmlHelper.php
> +    public function xmlDecode($content, SubmissionEntity $submission)
Yes

2020-09-29 11:41 UTC, vsolovei-smartling commented on readme.txt
> +* New behaviour of Auto synchronize properties on translated page with source expert profile setting. When turned on, extends support of ACF flexible fields in metadata.
Done

2020-09-29 11:54 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +        if (!is_array($source['meta'])) {
It seems to me that the original intention was to work with arrays, since everywhere we check for this property we try to init it with empty array if it doesn't exist or is falsy, and then work with it as an array

2020-09-29 14:36 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +            $xmlFields = [];
Done

2020-09-29 15:29 UTC, dimitrystd approved these changes

2020-09-29 17:23 UTC, merged