Add setting to link taxonomies instead of translating when possible
Smartling/wordpress-localization-plugin pull request #252
Opened 2020-10-02 13:31 UTC by vsolovei-smartling

2020-10-02 22:24 UTC, dimitrystd requested changes
Need to be discussed in voice

2020-10-02 22:24 UTC, dimitrystd commented on inc/Smartling/ContentTypes/CustomPostType.php
> +        ]);
Looks very similar to `ContentRelationsDiscoveryService.submissionExists`

2020-10-02 22:24 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +    public function findOriginalSubmission($contentType, $targetBlogId, $targetId, SubmissionEntity $previous = null)
I tried to understand this method but it's beyond my level.

Let's do it om example. I have a submission for taxonomy with
* sourceBlogId = 1
* sourceId = 1
* targetBlogId = 2
* targetId = 5

So I call function with params `("taxonomy", 2, 5)`. It finds my submission and calls itself with params `("taxonomy", 1, 1)`. And this is what I can understand. We have only one source blog and it should never appear in targetBlogId.
I'm afraid that your code can find something, but it can be not what you expected.

2020-10-05 08:36 UTC, PavelLoparev requested changes

2020-10-05 08:36 UTC, PavelLoparev commented on inc/Smartling/Bootstrap.php
> +            add_action('admin_init', static function () {
What is the point for making callbacks static?

2020-10-05 08:36 UTC, PavelLoparev commented on inc/Smartling/Bootstrap.php
> +        $data = $_POST['params'];
I'm afraid somewhere in the code it's expected to see changes in `$_POST['params']` (by $data reference)

2020-10-05 08:36 UTC, PavelLoparev commented on inc/Smartling/Bootstrap.php
> +        new PostTypes($di);
I don't get this. Something is happening in constructors?

2020-10-05 08:36 UTC, PavelLoparev commented on inc/Smartling/ContentTypes/CustomTaxonomyType.php
> +            $tag = 'wp.taxonomy.' . $this->getSystemName();
Seems like this never woked before since this method is not static

2020-10-05 15:32 UTC, vsolovei-smartling commented on inc/Smartling/Bootstrap.php
> +            add_action('admin_init', static function () {
Reader of the code may safely assume that the function changes no class properties

2020-10-05 15:34 UTC, vsolovei-smartling commented on inc/Smartling/Bootstrap.php
> +        $data = $_POST['params'];
No code changes $_POST['params'], I think it is safe to remove unneeded reference

2020-10-05 16:03 UTC, vsolovei-smartling commented on inc/Smartling/Bootstrap.php
> +        new PostTypes($di);
Yes, something is happening, the entire DI  I've tried to get rid of an unused variable and got unexpected results, so I've removed just the variable and added a comment above these

2020-10-05 16:03 UTC, vsolovei-smartling commented on inc/Smartling/ContentTypes/CustomTaxonomyType.php
> +            $tag = 'wp.taxonomy.' . $this->getSystemName();
Php is forgiving in this case, it works

2020-10-05 16:41 UTC, PavelLoparev commented on inc/Smartling/Bootstrap.php
> +            add_action('admin_init', static function () {
But you can change object properties in static function by passing `$this` through `use`. I mean static keyword applied to callback does not guarantee it won't change something. Or maybe I'm missing something?

2020-10-05 16:53 UTC, PavelLoparev commented on inc/Smartling/ContentTypes/CustomTaxonomyType.php
> +            $tag = 'wp.taxonomy.' . $this->getSystemName();
oh, it's not about method is static or not. it's about late static binding.

2020-10-19 11:51 UTC, closed without merging

2020-10-19 11:52 UTC, vsolovei-smartling commented
Superseded by #255