add blog switch logging
Smartling/wordpress-localization-plugin pull request #253
Opened 2020-10-05 10:23 UTC by vsolovei-smartling

2020-10-05 13:18 UTC, PavelLoparev requested changes

2020-10-05 13:18 UTC, PavelLoparev commented on inc/Smartling/Helpers/ContentHelper.php
> +            add_action('switch_blog', [$this, 'logSwitchBlog']);
Seems like this potentially adds action to hook multiple times per script execution. Maybe let's move this to constructor to not to remove this action every time in `ensureRestoredBlogId`?

2020-10-05 13:18 UTC, PavelLoparev commented on inc/Smartling/Helpers/ContentHelper.php
> +                    array_shift($args);
Didn't get why do you need to shift here. You don't need this var anywhere after this

2020-10-05 13:18 UTC, PavelLoparev commented on inc/Smartling/Helpers/ContentHelper.php
> +        $blog = $frame['args'][1];
Let's check if `$frame['args'][1]` is set before accessing it

2020-10-05 13:18 UTC, PavelLoparev commented on inc/Smartling/Helpers/ContentHelper.php
> +            $context = $frame['args'][3];
Let's check if `$frame['args'][3]` is set before accessing it

2020-10-05 15:19 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/ContentHelper.php
> +                    array_shift($args);
Removed

2020-10-05 16:37 UTC, PavelLoparev commented
Seems like this approach only covers subsequential blog switches as errors, but seems like it's not enough. I propose to check stack traces for `switchBlogId`/`restoreBlogId` (connector's methods) and if there are no mentions of these functions then it means switch was caused by external plugin/theme. it's still possible to use connector's code and call switch/restore in wrong order though

2020-10-07 17:06 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/ContentHelper.php
> +            $context = $frame['args'][3];
Done

2020-10-07 17:06 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/ContentHelper.php
> +            add_action('switch_blog', [$this, 'logSwitchBlog']);
WordPress calculates hashes for hooks, no harm in adding multiple times

2020-10-07 17:06 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/ContentHelper.php
> +        $blog = $frame['args'][1];
Done

2020-10-08 07:45 UTC, PavelLoparev approved these changes

2020-10-08 10:31 UTC, merged