add manual taxonomy linking (WP-534)
Smartling/wordpress-localization-plugin pull request #255
Opened 2020-10-09 12:04 UTC by vsolovei-smartling

2020-10-12 10:07 UTC, PavelLoparev requested changes

2020-10-12 10:07 UTC, PavelLoparev commented on inc/Smartling/WP/WPAbstractLight.php
> +        $this->renderViewScript($class . '.php');
Do you treat namespace as folders?

2020-10-12 10:07 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +    private function getMappedDiff(array $submissions, array $terms, $source)
Tests needed

2020-10-12 10:13 UTC, vsolovei-smartling commented on inc/Smartling/WP/WPAbstract.php
> -
Only usage for the function with this name is within Smartling\WP\Controller, there's a method in ControllerAbstract

2020-10-12 10:13 UTC, vsolovei-smartling commented on inc/Smartling/WP/WPAbstractLight.php
> +        $this->logger = $this->logger = MonologWrapper::getLogger(static::class);
Fixed

2020-10-12 10:31 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +        }, $filtered));
No, including $this would cause a php fatal error

2020-10-12 10:33 UTC, vsolovei-smartling commented on inc/Smartling/WP/View/BulkSubmit.php
> +$data = $this->viewData;
A property with both a getter and a setter at same accesibility level just causes unneeded clutter, no point in calling them, might as well read/alter the property directly

2020-10-12 10:34 UTC, vsolovei-smartling commented on inc/Smartling/WP/WPAbstractLight.php
> +        $this->renderViewScript($class . '.php');
Code copied from WPAbstract, but yes, it does

2020-10-12 11:41 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +        }, $filtered));
Oh, got it.

2020-10-12 17:06 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +    private function getMappedDiff(array $submissions, array $terms, $source)
Done

2020-10-13 19:43 UTC, dimitrystd commented on inc/Smartling/WP/WPAbstract.php
> -
It became harder to read code. The field is defined in base class but "get" property appears only in the successor. I think it should be close to the definition. And if you need to override "get" then you can define it again here.

2020-10-13 19:43 UTC, dimitrystd commented on inc/Smartling/WP/WPAbstractLight.php
> +class WPAbstractLight
The original `WPAbstract` was a collection of utility methods (there are no protected methods with business logic). Now we have two utility classes.
Can you point to which method in `WPAbstract` conflicted with `TaxonomyLinksController`?

2020-10-13 19:43 UTC, dimitrystd commented on readme.txt
> +* Added manual taxonomy linking between blogs
Added new UI (`Smartling` -> `Taxonomy links`) where you can link existing translated taxonomies with the source taxonomies. It helps connector to respect existing translations and use them in translated posts.

2020-10-15 10:14 UTC, vsolovei-smartling commented on inc/Smartling/WP/WPAbstractLight.php
> +class WPAbstractLight
Reverted

2020-10-15 10:15 UTC, vsolovei-smartling commented on readme.txt
> +* Added manual taxonomy linking between blogs
Done

2020-10-15 11:25 UTC, vsolovei-smartling commented on inc/Smartling/WP/WPAbstract.php
> -
Reverted

2020-10-15 13:39 UTC, PavelLoparev approved these changes

2020-10-15 13:39 UTC, PavelLoparev commented on inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
>  class WordpressFunctionProxyHelper
We have this class only for being able to mock WP's core functions? Built in functions can be mocked in namespaced code http://www.manuel-strehl.de/dev/overwrite_PHP_built-in_functions.en.html. Just curious why we decided to introduce this class.

2020-10-15 13:53 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
>  class WordpressFunctionProxyHelper
Probably, it was used for testing previously.

2020-10-15 23:03 UTC, dimitrystd commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +            wp_send_json_error('No changes');
Should we exit after this?

2020-10-15 23:03 UTC, dimitrystd commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +            wp_send_json_error('No changes');
Should we return json instead of a simple string?

2020-10-16 14:31 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +            wp_send_json_error('No changes');
This is a wordpress standard function to return data. No such function exists for returning strings

2020-10-16 14:31 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/TaxonomyLinksController.php
> +            wp_send_json_error('No changes');
No, there's an exit inside, and I've added this function to .metadata to inform phpstorm about that

2020-10-19 09:29 UTC, merged