Ignore unregistered post types on related submissions search
Smartling/wordpress-localization-plugin pull request #256
Opened 2020-10-09 17:18 UTC by vsolovei-smartling

2020-10-09 18:33 UTC, dimitrystd reviewed
In general looks good. I left a comment which can be ok

2020-10-09 18:33 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        if (!$this->getContentHelper()->checkEntityExists($curBlogId, $contentType, $id)) {
Before we returned the error and didn't execute code below. The new condition will write error to response but will continue to work.

2020-10-12 10:12 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        if (!$this->getContentHelper()->checkEntityExists($curBlogId, $contentType, $id)) {
Seems like lno because eventually it calls `wp_send_json` which calls `die` inside

2020-10-12 10:16 UTC, PavelLoparev requested changes

2020-10-12 10:16 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +                if (in_array($contentType, $registeredTypes, true)) {
Let's log this case for troubleshooting purposes (if not in array)

2020-10-12 10:19 UTC, PavelLoparev approved these changes
Left comment about logging

2020-10-12 17:51 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +                if (in_array($contentType, $registeredTypes, true)) {
Done

2020-10-12 18:03 UTC, merged