Respect excluded fields setting
Smartling/wordpress-localization-plugin pull request #258
Opened 2020-10-26 09:44 UTC by vsolovei-smartling

2020-10-26 09:45 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
> -    }
I strongly believe this function is useless, but interferes with normal testing flow

2020-10-26 10:34 UTC, PavelLoparev approved these changes
Left some comments/questions that I want to clarify before merging

2020-10-26 10:34 UTC, PavelLoparev commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        return array_map('trim', explode(PHP_EOL, $this->stateFields['filter_skip']));
`return array_map('trim', explode(PHP_EOL, $this->getFilterSkip()));`

2020-10-26 10:34 UTC, PavelLoparev commented on inc/config/services.yml
> +      - "@wp.proxy"
Do we have places where we manually instantiate this object (except tests)? We need to pass proxy there as well if any

2020-10-26 10:34 UTC, PavelLoparev commented on inc/Smartling/Submissions/SubmissionEntity.php
> +    public function getLockedFieldsArray()
I don't see where you use this function

2020-10-26 10:39 UTC, PavelLoparev commented on inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
> -    }
The function looks ok to me - just returns new object without some fields. Questions:
1. Where in code we use `clone`? I'm afraid after this change we will brake some flow(s)
2. Could you provide example on how it interferes testing flow?

2020-10-26 10:40 UTC, PavelLoparev requested changes
Approved request by incident last time

2020-10-26 11:21 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
> -    }
__clone should not return something, but rather change cloned object properties. This is not happening, as resultToEntity creates a new object, alters it's properties and returns it (to be discarded in __clone).
Cloning happens multiple times in code, mostly while reading content, a clone of entity is returned.
When cloning a PhpUnitMockObject, it's mocked functions start returning nulls.

2020-10-26 11:23 UTC, vsolovei-smartling commented on inc/config/services.yml
> +      - "@wp.proxy"
No, everything is handled, and should be handled by DI

2020-10-26 11:25 UTC, vsolovei-smartling commented on inc/Smartling/Submissions/SubmissionEntity.php
> +    public function getLockedFieldsArray()
Removed

2020-10-26 11:26 UTC, vsolovei-smartling commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        return array_map('trim', explode(PHP_EOL, $this->stateFields['filter_skip']));
Chanded

2020-10-26 16:39 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
> -    }
Reverted to reintroduce change in a future pr

2020-10-26 16:56 UTC, PavelLoparev approved these changes

2020-10-27 10:46 UTC, merged

2020-10-30 18:07 UTC, dimitrystd reviewed
@vsolovei-smartling I added desired update for readme. Will push it with the next release.
Also, it will be nice to add new unit tests instead of adding complexity to existing. It can be not clear how assert is important during refactoring in the far future.

2020-10-30 18:07 UTC, dimitrystd commented on readme.txt
> +* Auto synchronize properties on translated page with source feature doesn't alter locked and excluded fields
It's a little bit hard to read when you don't know\remember feature names.

---

The feature `Auto synchronize properties on translated page with source` now doesn't alter locked and excluded fields on the target page