remove EntityAbstract->__clone(), set 1.15.1 stable, fix TaxonomyEntityStd->setMetaTag()
Smartling/wordpress-localization-plugin pull request #260
Opened 2020-10-28 11:05 UTC by vsolovei-smartling

remove seemingly useless clone function in EntityAbstract
remove ContentHelper WordpressFunctionProxyHelper dependency

2020-10-28 11:06 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
> -    }
Php clone function should alter current object, this seems useless

2020-10-28 11:07 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/TaxonomyEntityStd.php
> +        if ($curValue !== $tagValue) {
Previously, we always entered the branch, altering curValue

2020-10-28 11:07 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> -        $this->entityNotFound(WordpressContentTypeHelper::CONTENT_TYPE_WIDGET, $guid);
No such class constant

2020-10-30 10:47 UTC, PavelLoparev requested changes

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> +        }
Did you find the place where this exception might be thrown? Is it being caught somewhere?

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> -        $this->entityNotFound(WordpressContentTypeHelper::CONTENT_TYPE_WIDGET, $guid);
So, before it threw php notices? Or failed?

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> +    public function getAll($limit = 0, $offset = 0, $orderBy = '', $order = '', $searchString = '')
So, orderBy, order and searchString are never used here?

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
> +    public function getAll($limit = 0, $offset = 0, $orderBy = '', $order = '', $searchString = '')
Seems like orderBy, order and searchString vars are never used here

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> -        return $result;
Seems like it was manual slicing? Can we add some tests to make sure before/after results are the same?

2020-10-30 10:47 UTC, PavelLoparev commented on inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
> +        }
Where do we handle this exception and do we?

2020-10-30 10:47 UTC, PavelLoparev commented on inc/config/services.yml
> -      - "@wp.proxy"
Didn't get why you delete this dependency. It is never used?

2020-10-30 11:10 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> +    public function getAll($limit = 0, $offset = 0, $orderBy = '', $order = '', $searchString = '')
No, they're unused, but I can't remove them as the parent's signature would be different

2020-10-30 11:10 UTC, vsolovei-smartling commented on inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
> +    public function getAll($limit = 0, $offset = 0, $orderBy = '', $order = '', $searchString = '')
Same, depends on parent signature

2020-10-30 11:13 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> -        $this->entityNotFound(WordpressContentTypeHelper::CONTENT_TYPE_WIDGET, $guid);
It's likely nobody uses widgets translation for now, it would've failed

2020-10-30 11:15 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> +        }
Previously, the code would fail next line, when calling $this->getWidgetHelperInstance($entity), as the function does not allow for null values. I'm replacing the built-in exception with a defined exception, but do not catch it.

2020-10-30 11:16 UTC, vsolovei-smartling commented on inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
> +        }
Same as in WidgetEntity, we don't

2020-10-30 11:16 UTC, vsolovei-smartling commented on inc/config/services.yml
> -      - "@wp.proxy"
Yes, I've added it in #258, but it is not used

2020-11-02 14:10 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
> -        return $result;
I've added a test that passes on both current master and this branch

2020-11-02 14:23 UTC, PavelLoparev approved these changes

2020-11-02 23:42 UTC, dimitrystd approved these changes

2020-11-04 14:26 UTC, merged