add url rewrite plugin example
Smartling/wordpress-localization-plugin pull request #261
Opened 2020-10-30 07:25 UTC by vsolovei-smartling

2020-10-30 10:50 UTC, PavelLoparev commented
Is it just copy-paste from existing "stand-alone" plugin from Help Center? We just want to merge it to the connector's code base? Or is it new plugin?

2020-10-30 10:50 UTC, PavelLoparev reviewed
Is it just copy-paste from existing "stand-alone" plugin from Help Center? We just want to merge it to the connector's code base? Or is it new plugin?

2020-10-30 11:09 UTC, vsolovei-smartling commented
> Is it just copy-paste from existing "stand-alone" plugin from Help Center? We just want to merge it to the connector's code base? Or is it new plugin?

It's been slightly altered: a new option was added to check if a link is accessible, the locale detection was improved, as recent plugin versions do not store this info in submission. I also will update the Help Center. Adding the example plugin to code base will allow us to supply updates and add tests potentially

2020-10-30 11:24 UTC, PavelLoparev requested changes

2020-10-30 11:24 UTC, PavelLoparev commented on plugin-examples/url-rewrite.php
> +                return $result;
In case of exception you will return modified tag. i think you should return original tag if you failed to verify content

2020-11-02 09:51 UTC, vsolovei-smartling commented on plugin-examples/url-rewrite.php
> +                return $result;
Done

2020-11-02 09:58 UTC, merged