WP-561-menu-items-translation
Smartling/wordpress-localization-plugin pull request #265
Opened 2020-11-13 13:41 UTC by vsolovei-smartling

2020-11-13 19:27 UTC, dimitrystd requested changes
Let's invert logic. Instead of pass "flag" through pipeline we should change all callers to call pipeline (get related items) only if it's required.

2020-11-17 14:26 UTC, PavelLoparev reviewed
In general, seems like  you just added one condition into each content entity type upload flow.

Probably the question are all the existing tests passed? And do we have test for menu items specifically?

2020-11-17 14:26 UTC, PavelLoparev commented on js/smartling-connector-admin.js
> -                if (wp && wp.data && wp.data.dispatch && wp.data.dispatch('core/notices').createSuccessNotice && wp.data.dispatch('core/notices').createErrorNotice) {
I remember it was added in previous PR. Why delete this now?

2020-11-17 15:07 UTC, vsolovei-smartling commented
> In general, seems like you just added one condition into each content entity type upload flow.
> 
> Probably the question are all the existing tests passed? And do we have test for menu items specifically?

Except the one uncoditional call, yes.
Test pass, I'm currently trying to implement a menu items test

2020-11-17 15:07 UTC, vsolovei-smartling commented on js/smartling-connector-admin.js
> -                if (wp && wp.data && wp.data.dispatch && wp.data.dispatch('core/notices').createSuccessNotice && wp.data.dispatch('core/notices').createErrorNotice) {
The client in question reported it only makes matters worse for them

2020-11-18 00:04 UTC, dimitrystd approved these changes

2020-11-18 20:54 UTC, dimitrystd approved these changes

2020-11-23 10:00 UTC, merged