Add media attachments UI (WP-568)
Smartling/wordpress-localization-plugin pull request #269
Opened 2021-01-28 15:16 UTC by vsolovei-smartling

2021-01-28 15:21 UTC, vsolovei-smartling commented on inc/Smartling/DI.php
> +class DI
I initially tried to untangle DITrait, which is not in fact a trait, but the resulting changeset was too large. (https://bt.smartling.net/browse/WP-570)

2021-01-29 12:40 UTC, PavelLoparev requested changes
Left few minot comments and some related to new `DI` class.

Additionally, I would like to have a small demo (maybe you could show it on today's friday internal demo?) to see how it looks like.

2021-01-29 12:40 UTC, PavelLoparev commented on inc/Smartling/Tuner/MediaAttachmentRulesManager.php
> +    }
Is it empty by intention?

2021-01-29 12:40 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/AdminPage.php
> +                $manager = (new DI())->fromContainer('media.attachment.rules.manager');
Shouldn't the `DI` be a singleton? You create new DI instance with own ContainerBuilder inside each time you call `new DI()`. It means you will have N containers with own service registry.

2021-01-29 12:40 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/AdminPage.php
> +                $manager = (new DI())->fromContainer('media.attachment.rules.manager');
And in general seems like you've implemented `service locator` pattern which is treated as antipattern. You should inject  `'media.attachment.rules.manager'` dependency from outside rather than resolve it inside the code which depends on this service.

2021-01-29 12:40 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/MediaRuleForm.php
> +        wp_redirect(get_site_url() . '/wp-admin/admin.php?page=smartling_customization_tuning');
Minor: maybe `smartling_customization_tuning` -> `smartling_media_attachments_settings`?

2021-01-29 12:40 UTC, PavelLoparev commented on tests/Smartling/Helpers/RelativeLinkedAttachmentCoreHelperTest.php
> +        ]);
Minor: why do you mock this return? Seems like it should return this array as default values since you have defined them in yml file as build in wordpress values

2021-01-29 14:59 UTC, vsolovei-smartling commented on inc/Smartling/Tuner/MediaAttachmentRulesManager.php
> +    }
Yes, it is required by interface, but nothing to do for this particular manager

2021-01-29 15:01 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/MediaRuleForm.php
> +        wp_redirect(get_site_url() . '/wp-admin/admin.php?page=smartling_customization_tuning');
This is handled in the root controller, the url is correct

2021-01-29 15:11 UTC, vsolovei-smartling commented on tests/Smartling/Helpers/RelativeLinkedAttachmentCoreHelperTest.php
> +        ]);
I'm used to not working with di container in tests, it's faster to mock the object

2021-01-29 15:12 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/AdminPage.php
> +                $manager = (new DI())->fromContainer('media.attachment.rules.manager');
Fortunately, this could be reworked. I thought that the filter ui service is invoked from wordpress, and I'm unable to add any parameters

2021-01-29 16:10 UTC, PavelLoparev commented on tests/Smartling/Helpers/RelativeLinkedAttachmentCoreHelperTest.php
> +        ]);
There might be a situation when you change defaults in the YAML file but don't change the test and the test will pass, but in reality, something may be broken.

2021-01-29 16:36 UTC, vsolovei-smartling commented on tests/Smartling/Helpers/RelativeLinkedAttachmentCoreHelperTest.php
> +        ]);
The results of the method's call are configuration dependent, yes, but here we are testing with two arbitrary rules and ensure that the translation goes as expected.

2021-01-29 17:03 UTC, PavelLoparev commented on tests/Smartling/Helpers/RelativeLinkedAttachmentCoreHelperTest.php
> +        ]);
agree. resolved

2021-01-29 17:03 UTC, PavelLoparev approved these changes

2021-01-29 17:57 UTC, dimitrystd requested changes

2021-01-29 17:57 UTC, dimitrystd commented on inc/Smartling/Tuner/MediaAttachmentRulesManager.php
> +    }
Then why not remove `implements WPHookInterface`?

2021-01-29 17:57 UTC, dimitrystd commented on inc/Smartling/Services/SmartlingFilterUiService.php
> +    public function __construct(MediaAttachmentRulesManager $mediaAttachmentRulesManager)
I didn't get the reason to inject this manager from view. Other managers are instantiated right in this class.

2021-02-01 10:31 UTC, vsolovei-smartling commented on inc/Smartling/Services/SmartlingFilterUiService.php
> +    public function __construct(MediaAttachmentRulesManager $mediaAttachmentRulesManager)
It's not injected from view, but from DI container (https://github.com/Smartling/wordpress-localization-plugin/pull/269/files#diff-78c7355521f118c31dd783b39acaead8f82ff908569067475b749340eb8ed4feR29)

2021-02-01 10:31 UTC, vsolovei-smartling commented on inc/Smartling/Tuner/MediaAttachmentRulesManager.php
> +    }
Removed

2021-02-05 10:10 UTC, merged