add smartling job column to translation progress (WP-577)
Smartling/wordpress-localization-plugin pull request #274
Opened 2021-04-07 14:35 UTC by vsolovei-smartling

2021-04-09 11:30 UTC, PavelLoparev reviewed
Too many unrelated changes, hard to review. But as I get the idea was to introduce some dto that represents jobs info and use it across the code. 2 questions:
1. I didn't see where we show this job name info on UI.
2. Maybe it would better to show not only job name bat also generate a link to dashboard with job? It will require to store job uid as well.

In general LGTM

2021-04-22 02:28 UTC, dimitrystd requested changes

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Jobs/JobInformationManager.php
> +        if ($id === 0) {
Do you really get 0 when it's duplicate?

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Jobs/JobInformationManager.php
> +            'INSERT INTO %1$s (%2$s, %3$s, %4$s, %5$s, %6$s) values (\'%7$s\', \'%8$s\', \'%9$s\', \'%10$s\', \'%11$s\') ON DUPLICATE KEY UPDATE %2$s = \'%7$s\', %6$s = \'%11$s\'',
Does `db` has parametrized query? SQL concatenation will be a blocker for any security review (which is not unique case for us). SF already scanned us and found js injection. They will find this too.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Jobs/JobInformationManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
let's add a column and its value here.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Jobs/SubmissionJobEntity.php
> +                'type' => 'unique',
This index lock you to have 1:1 relationship between jobs and submissions. Why do we need this table then? Let's discuss on a call.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +     */
Didn't get this change. In other places, you remove comments by adding types. Here you do the oposite.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionEntity.php
> +            return new JobInformationEntity('', '', '');
Usually class has static field `empty` that returns such objects

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionEntity.php
> +    public function getJobInfoWithBatchUid(): JobInformationEntityWithBatchUid
Having these 3 fields make design very complex. Have no suggestions right now. Let's fix other issues but return to this question before the release.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionManager.php
> +        if ($result->getId() !== null) {
I don't think it's a good idea to enrich one by one submission. It should be in bulk when we get a list of submissions. It's priority number 2 or 3. But we should address it before we will get weird bug reports about high CPU.

2021-04-22 02:28 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionManager.php
> +        $block->addCondition(Condition::getCondition(ConditionBuilder::CONDITION_SIGN_EQ, SubmissionEntity::FIELD_BATCH_UID, [$batchUid]));
I can't say that such inlining really helps to read\maintain code.

2021-04-22 10:38 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/DB.php
> -        $classes = [
Wrong base chosen for pr, fixed

2021-04-22 10:39 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/QueryBuilder/QueryBuilder.php
> +                $preOptions[] = true ? "`$field` $value" : "$field $value";
Once again, wrong base, fixed.
escapeName() is used to escape a string value, it's likely to break things when trying to escape a field name

2021-04-22 10:41 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobInformationEntity.php
> +class JobInformationEntity implements SmartlingTableDefinitionInterface
It's consistent with previous usages
https://github.com/Smartling/wordpress-localization-plugin/blob/b50dcca35a6ef5ceaf71196cd690e7476bd456fa/inc/Smartling/Submissions/SubmissionEntity.php#L42
https://github.com/Smartling/wordpress-localization-plugin/blob/b50dcca35a6ef5ceaf71196cd690e7476bd456fa/inc/Smartling/Base/SmartlingEntityAbstract.php#L15
but basically, it's the same, entities get passed to a manager that does DB related operations

2021-04-22 10:42 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobInformationEntity.php
> +                'type' => 'unique',
Not sure: I think a particular jobUid always belongs to the same projectUid, if that is the case, we would only be increasing the index size

2021-04-22 10:43 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobInformationManager.php
> +        if ($id === 0) {
Yes

2021-04-22 10:45 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobInformationManager.php
> +            'INSERT INTO %1$s (%2$s, %3$s, %4$s, %5$s, %6$s) values (\'%7$s\', \'%8$s\', \'%9$s\', \'%10$s\', \'%11$s\') ON DUPLICATE KEY UPDATE %2$s = \'%7$s\', %6$s = \'%11$s\'',
Not yet, we could implement it over wpdb->prepare()

2021-04-22 10:46 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobInformationManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
Done

2021-04-22 10:47 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +     */
wrong base for pr, fixed

2021-04-22 10:48 UTC, vsolovei-smartling commented on inc/Smartling/Submissions/SubmissionEntity.php
> +            return new JobInformationEntity('', '', '');
Didn't get this comment, let's discuss on call

2021-04-22 10:50 UTC, vsolovei-smartling commented on inc/Smartling/Submissions/SubmissionManager.php
> +        $block->addCondition(Condition::getCondition(ConditionBuilder::CONDITION_SIGN_EQ, SubmissionEntity::FIELD_BATCH_UID, [$batchUid]));
In this particular case, we add an inlined condition on the next line
https://github.com/Smartling/wordpress-localization-plugin/blob/b50dcca35a6ef5ceaf71196cd690e7476bd456fa/inc/Smartling/Submissions/SubmissionManager.php#L352

2021-04-22 17:33 UTC, dimitrystd requested changes

2021-04-22 17:33 UTC, dimitrystd commented on inc/Smartling/Jobs/JobEntity.php
> +        return new JobEntity('', '', '');
ideally it should be singleton

2021-04-22 17:33 UTC, dimitrystd commented on inc/Smartling/Jobs/JobManager.php
> +            'INSERT INTO %1$s (%2$s, %3$s, %4$s, %5$s, %6$s) values (\'%7$s\', \'%8$s\', \'%9$s\', \'%10$s\', \'%11$s\') ON DUPLICATE KEY UPDATE %2$s = \'%7$s\', %6$s = \'%11$s\'',
Forgot to update all queries in this class

2021-04-22 17:33 UTC, dimitrystd commented on inc/Smartling/Jobs/SubmissionsJobsManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
Add field name and its value into error message

2021-04-22 17:33 UTC, dimitrystd commented on inc/Smartling/DbAl/DB.php
> +    public function prepare(string $query, ...$args): string
Do we really need to make it public and expose it in interface?

2021-04-22 19:38 UTC, vsolovei-smartling commented on inc/Smartling/DbAl/DB.php
> +    public function prepare(string $query, ...$args): string
Made private; removed from interface

2021-04-22 19:38 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/SubmissionsJobsManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
Done

2021-04-22 19:38 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobManager.php
> +            'INSERT INTO %1$s (%2$s, %3$s, %4$s, %5$s, %6$s) values (\'%7$s\', \'%8$s\', \'%9$s\', \'%10$s\', \'%11$s\') ON DUPLICATE KEY UPDATE %2$s = \'%7$s\', %6$s = \'%11$s\'',
Fixed

2021-04-22 19:38 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobEntity.php
> +        return new JobEntity('', '', '');
didn't get this comment

2021-04-22 21:31 UTC, dimitrystd commented on inc/Smartling/Jobs/JobEntity.php
> +        return new JobEntity('', '', '');
```php
private static self $_empty = new JobEntity('', '', '');
public static function empty(): self
{
    return $_empty
}
```
So you always return the same object. Like a const but for object types.

2021-04-22 21:31 UTC, dimitrystd commented on inc/Smartling/Jobs/SubmissionsJobsManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
Well, beter to use splunk friendly format
```php
throw new EntityNotFoundException("Unable to get entity where \"$field\"=$id");
```

2021-04-22 21:32 UTC, dimitrystd approved these changes
Approve, but left two minor comments

2021-04-23 13:20 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobEntity.php
> +        return new JobEntity('', '', '');
I got it now, but think it can't be done, as php doesn't allow for expressions (new xxx) as default field values.

2021-04-23 13:20 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/SubmissionsJobsManager.php
> +            throw new EntityNotFoundException('Unable to get entity');
Done

2021-04-26 09:21 UTC, merged