option to set post status to draft on translation completed
Smartling/wordpress-localization-plugin pull request #277
Opened 2021-04-28 16:05 UTC by vsolovei-smartling

2021-04-28 22:54 UTC, dimitrystd requested changes

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
>                              'Submission id=%s (blog=%s, item=%s, content-type=%s) setting status %s for translation. Profile snapshot: %s',
I have seen this log. Really don't understand why do we need **entire config** dump into log. I would recommend to remove snapshot from the log since we touch this logic.

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +                            throw new \RuntimeException('Unexpected value for profile setting regarding asset status on translation completion');
Include `$onCompletedTranslation` value into error. Something like
```php
throw new \RuntimeException('Unexpected value=%d in profile setting for Publish translated post');
```

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +    public function getChangeAssetStatusOnCompletedTranslation(): int
Just for discussion. I don't have objections regarding this name. But we may consider to keep it consistent with other connectors (yes, java connectors). We call it there
* Enum [TranslationPublishingMode](https://github.com/Smartling/zendesk-connector/blob/master/shared/src/main/java/com/smartling/connector/zendesk/core/settings/TranslationPublishingMode.java)
* Property [translationPublishingMode](https://github.com/Smartling/zendesk-connector/blob/master/shared/src/main/java/com/smartling/connector/zendesk/core/settings/ZendeskSettings.java#L42)

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        $state['target_locales'] = json_encode($serializedTargetLocales, JSON_THROW_ON_ERROR);
Pls keep compatibility with 7.2 so far.

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +     * Alias for $this->setChangeAssetStatusOnCompletedTranslation, required for EntityAbstract::fromArray();
Sorry, didn't get it. Can we just update method in base class?

2021-04-28 22:54 UTC, dimitrystd commented on inc/Smartling/WP/Controller/ConfigurationProfileFormController.php
> -            $profile->setCallBackUrl($settings['callbackUrl'] === 'on');
Didn't get what it was. Hope it's safe to remove this logic.

2021-04-28 22:54 UTC, dimitrystd commented on readme.txt
> +* Added possibility to set assets to Draft status after completed translations are downloaded
Just want to make it more user-friendly
```
* Added more Publish options for delivering translated posts. Now you can choose what to do with fresh delivered translated post: just deliver and do nothing; always deliver as `Draft`; always deliver as `Published`
```

BTW, actually I don't understand the 1st option :). We probably should specify what exactly happens with post when you update content.

2021-04-29 06:44 UTC, PavelLoparev commented on readme.txt
> +* Added possibility to set assets to Draft status after completed translations are downloaded
I think there are only 2 options: deliver as draft and deliver as publoshed.

2021-04-29 06:47 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/ConfigurationProfileFormController.php
> -            $profile->setCallBackUrl($settings['callbackUrl'] === 'on');
Seems like it was setting up boolean value as a callback url..? I'm also not sure about this.

2021-04-29 06:54 UTC, PavelLoparev commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        $state['target_locales'] = json_encode($serializedTargetLocales, JSON_THROW_ON_ERROR);
It's strange, on WP site PHP requirement for the plugin is php >= 7.2, but in composer JSON file php >=7.4. So, I think it's safe to use `JSON_THROW_ON_ERROR` (since it was added in php 7.3) here but we definitely need to change the requirements section on the plugin's page.

![image](https://user-images.githubusercontent.com/9624816/116512274-71275880-a8d0-11eb-9f34-5cd91fe9d7a9.png)
![image](https://user-images.githubusercontent.com/9624816/116512464-c1061f80-a8d0-11eb-9cf7-aae1bd82951d.png)

2021-04-29 06:54 UTC, PavelLoparev commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        $state['target_locales'] = json_encode($serializedTargetLocales, JSON_THROW_ON_ERROR);
It's strange, on WP site PHP requirement for the plugin is php >= 7.2, but in composer JSON file php >=7.4. So, I think it's safe to use `JSON_THROW_ON_ERROR` (since it was added in php 7.3) here but we definitely need to change the requirements section on the plugin's page.

![image](https://user-images.githubusercontent.com/9624816/116512274-71275880-a8d0-11eb-9f34-5cd91fe9d7a9.png)
![image](https://user-images.githubusercontent.com/9624816/116512464-c1061f80-a8d0-11eb-9cf7-aae1bd82951d.png)

2021-04-29 06:56 UTC, PavelLoparev requested changes
Looks ok to me except for Dmitry's comments.

2021-04-29 09:15 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
>                              'Submission id=%s (blog=%s, item=%s, content-type=%s) setting status %s for translation. Profile snapshot: %s',
Removed

2021-04-29 09:15 UTC, vsolovei-smartling commented on inc/Smartling/Base/SmartlingCoreUploadTrait.php
> +                            throw new \RuntimeException('Unexpected value for profile setting regarding asset status on translation completion');
Done

2021-04-29 09:15 UTC, vsolovei-smartling commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +    public function getChangeAssetStatusOnCompletedTranslation(): int
Done

2021-04-29 09:16 UTC, vsolovei-smartling commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +        $state['target_locales'] = json_encode($serializedTargetLocales, JSON_THROW_ON_ERROR);
Done

2021-04-29 09:22 UTC, vsolovei-smartling commented on inc/Smartling/Settings/ConfigurationProfileEntity.php
> +     * Alias for $this->setChangeAssetStatusOnCompletedTranslation, required for EntityAbstract::fromArray();
Unfortunately, the change would be time consuming. Currently all entities extend SmartlingEntityAbstract, which is used in many places. After reading a row from database, a manager calls SmartlingEntityAbstract->fromArray()(https://github.com/Smartling/wordpress-localization-plugin/blob/76a307a56c09e9cd9cf366362634862630331298/inc/Smartling/Base/SmartlingEntityAbstract.php#L145) that sets all fields of the entity, and, since we have __set, the methods in the entity get called.
I would love to get rid of this, but it's a time consuming process, so definitely not this pr

2021-04-29 09:23 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/ConfigurationProfileFormController.php
> -            $profile->setCallBackUrl($settings['callbackUrl'] === 'on');
No field in db to store the value, no getters or setters in code, I think it's safe.

2021-04-29 09:25 UTC, vsolovei-smartling commented on readme.txt
> +* Added possibility to set assets to Draft status after completed translations are downloaded
No, it is in fact, 3 options, no change, draft, publish. This setting only controls the resulting post status after completing translation. No change does no changes, draft sets post_status to draft, publish sets post_status to publish

2021-04-29 09:28 UTC, PavelLoparev approved these changes

2021-04-29 19:27 UTC, dimitrystd approved these changes
Looks good. Only left a comment to update the wording.

2021-04-29 19:27 UTC, dimitrystd commented on inc/Smartling/WP/View/ConfigurationProfileForm.php
> +                                ConfigurationProfileEntity::TRANSLATION_PUBLISHING_MODE_DRAFT => __('Draft', $domain),
Pls update the labels:
* Don't change status
* Always publish
* Always draft

2021-04-29 19:27 UTC, dimitrystd commented on readme.txt
> +* Added more publish options for delivering translated posts. Now you can choose what post status to choose after delivering: don't change existing status; set to 'draft'; set to 'published'
Why do you use single quotes instead of backquote `. I especially used it to highlight words

2021-04-29 19:27 UTC, dimitrystd commented on readme.txt
> +* Added more publish options for delivering translated posts. Now you can choose what post status to choose after delivering: don't change existing status; set to 'draft'; set to 'published'
Also, replace one more word
```suggestion
* Added more publish options for delivering translated posts. Now you can choose what post status to set after delivering: don't change existing status; set to `draft`; set to `published`
```

2021-04-30 09:22 UTC, merged