add example Gutenberg block attachment url rewrite
Smartling/wordpress-localization-plugin pull request #281
Opened 2021-05-19 06:57 UTC by vsolovei-smartling

2021-05-19 12:20 UTC, PavelLoparev approved these changes

2021-05-20 15:15 UTC, dimitrystd requested changes

2021-05-20 15:15 UTC, dimitrystd commented on plugin-examples/attachment-url-rewrite.php
> +                $siteHelper->restoreBlogId();
Put into `finally`

2021-05-20 15:15 UTC, dimitrystd commented on plugin-examples/attachment-url-rewrite.php
> +                    $blockAttributes[$blockAttribute] = $post->guid;
I got lost here. I thought we will update `backgroundMediaUrl` in this plugin

2021-05-20 15:30 UTC, vsolovei-smartling commented on plugin-examples/attachment-url-rewrite.php
> +function replaceProperties(GutenbergBlock $block, array $attributes, SiteHelper $siteHelper, int $targetBlogId): GutenbergBlock
It's not a part of any class, it would be if it was

2021-05-20 15:30 UTC, vsolovei-smartling commented on plugin-examples/attachment-url-rewrite.php
> +                $siteHelper->restoreBlogId();
Refactored

2021-05-21 12:13 UTC, vsolovei-smartling commented on plugin-examples/attachment-url-rewrite.php
> +    add_action('smartling_after_deserialize_content', static function (AfterDeserializeContentEventParameters $params) {
It doesn't work for network admin panels after all, reverted the change

2021-05-26 12:33 UTC, merged