fix download issue on related content not found
Smartling/wordpress-localization-plugin pull request #286
Opened 2021-06-10 12:09 UTC by vsolovei-smartling

2021-06-10 12:39 UTC, dimitrystd requested changes

2021-06-10 12:39 UTC, dimitrystd commented on readme.txt
> +* Fixed an issue with downloads
Pls add detail about an issue. Unfortunately, I don't understand from code and there is no jira ticket.

2021-06-10 13:08 UTC, vsolovei-smartling commented on readme.txt
> +* Fixed an issue with downloads
I've added a Jira ticket (https://bt.smartling.net/browse/WP-600) with more details. This issue occurs when RelativeLinkedAttachmentCoreHelper tries to get attachment ID for an ID, but that id is not an attachment, and getAttachmentId returns null.

2021-06-10 13:23 UTC, dimitrystd commented on readme.txt
> +* Fixed an issue with downloads
Then let it be
```
Fixed an issue with downloads when the post has related assets
```

2021-06-10 15:41 UTC, dimitrystd approved these changes

2021-06-11 08:11 UTC, PavelLoparev approved these changes

2021-06-11 13:09 UTC, merged