add job name search to translation progress (WP-611)
Smartling/wordpress-localization-plugin pull request #296
Opened 2021-07-14 08:26 UTC by vsolovei-smartling

2021-07-14 09:01 UTC, PavelLoparev commented on inc/Smartling/WP/Table/SubmissionTableWidget.php
> +                JobEntity::FIELD_JOB_NAME,
Didn't get it, we replaced the filter by source title with filter by job name?

2021-07-14 09:50 UTC, vsolovei-smartling commented on inc/Smartling/WP/Table/SubmissionTableWidget.php
> +                JobEntity::FIELD_JOB_NAME,
SubmissionEntity::FIELD_SOURCE_TITLE was present twice in the array, I've replaced one occurence with Job Name

2021-07-15 10:09 UTC, PavelLoparev requested changes
`QueryBuilder` is used not only in submission s manager class. Could we also cover with tests existing queries generated by query builder?
- In `Queue.php`
- In `MultilingualPressConnector.php`
- In `AbsoluteLinkedAttachmentCoreHelper.php`
- In `JobAbstract.php`
- In `SettingsManager.php`
- In `AcfOptionEntity.php`

2021-07-15 11:09 UTC, vsolovei-smartling commented on tests/Smartling/Submissions/SubmissionManagerTest.php
> +        $db->expects($this->once())->method('fetch')->with("SELECT COUNT(DISTINCT s.id) AS cnt\n     FROM wp_smartling_submissions AS s\n        LEFT JOIN wp_smartling_submissions_jobs AS sj ON s.id
The manager only uses whatever conditions were provided. Changed to reduce confusion in  103146d2f89df7c081a6488df38d0f45cb28803e

2021-07-15 15:51 UTC, vsolovei-smartling commented on tests/Smartling/Submissions/SubmissionManagerTest.php
> +        $db->expects($this->once())->method('fetch')->with("SELECT COUNT(DISTINCT s.id) AS cnt\n     FROM wp_smartling_submissions AS s\n        LEFT JOIN wp_smartling_submissions_jobs AS sj ON s.id
Done

2021-07-16 09:48 UTC, PavelLoparev approved these changes
I'm against this approach with manual sql query generation. But since it's already used in the project it seems like refactoring is out of this task's scope.

Did you try to run these new tests on current master branch? I just want to make sure that existing queries are not affected and only one query is changed.

2021-07-16 11:35 UTC, vsolovei-smartling commented
Yes, I got that intent and ran them on master. Only failing tests were for SubmissionManager, but this was expected, as they are changed in branch.

2021-07-16 12:06 UTC, PavelLoparev commented
Ok, great

2021-07-19 08:25 UTC, merged