add setting to disable automatic smartling lock id generation (WP-613)
Smartling/wordpress-localization-plugin pull request #298
Opened 2021-07-27 13:50 UTC by vsolovei-smartling

2021-07-27 14:43 UTC, PavelLoparev requested changes

2021-07-27 14:43 UTC, PavelLoparev commented on build/assets/js/smartling-locked.js
> +                            help={props.attributes[LOCKED] ? __('Content will not change on translation') : __('Content will change on translation')}
Is `__()` used for UI strings translation?

2021-07-27 14:43 UTC, PavelLoparev commented on inc/Smartling/Bootstrap.php
> +        GlobalSettingsManager::setGenerateLockIdsFrontend($data['handleRelationsManually'] === "1");
Why we enable automatic block id generation only if `handleRelationsManually` is enabled?

2021-07-27 14:43 UTC, PavelLoparev commented on inc/Smartling/Services/GlobalSettingsManager.php
> +    }
Should be constant instead, I think

2021-07-27 14:43 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
> +                    if (GlobalSettingsManager::isGenerateLockIdsFrontend()) {
It doesn't sound right. I would prefer to have name like `isGenerateLockIdsEnabled`.

2021-07-27 14:43 UTC, PavelLoparev commented on inc/Smartling/WP/View/ConfigurationProfiles.php
> +                        <th><label for="<?= GlobalSettingsManager::SMARTLING_FRONTEND_GENERATE_LOCK_IDS ?>">Generate lock ids on editing content</label></th>
Should this string be wrapped to `__()`?

2021-07-27 16:27 UTC, vsolovei-smartling commented on build/assets/js/smartling-locked.js
> +                            help={props.attributes[LOCKED] ? __('Content will not change on translation') : __('Content will change on translation')}
Yes

2021-07-27 16:27 UTC, vsolovei-smartling commented on inc/Smartling/Bootstrap.php
> +        GlobalSettingsManager::setGenerateLockIdsFrontend($data['handleRelationsManually'] === "1");
Fixed

2021-07-27 16:35 UTC, vsolovei-smartling commented on inc/Smartling/Services/GlobalSettingsManager.php
> +    }
It serves no purpose, I've inlined all similar constants for consistency

2021-07-27 16:35 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
> +                    if (GlobalSettingsManager::isGenerateLockIdsFrontend()) {
Done

2021-07-27 16:36 UTC, vsolovei-smartling commented on inc/Smartling/WP/View/ConfigurationProfiles.php
> +                        <th><label for="<?= GlobalSettingsManager::SMARTLING_FRONTEND_GENERATE_LOCK_IDS ?>">Generate lock ids on editing content</label></th>
Done

2021-07-28 10:55 UTC, PavelLoparev approved these changes

2021-07-29 06:58 UTC, merged