fix WP proxy (WP-636)
Smartling/wordpress-localization-plugin pull request #318
Opened 2021-09-14 21:19 UTC by vsolovei-smartling

2021-09-14 23:29 UTC, dimitrystd approved these changes

2021-09-14 23:29 UTC, dimitrystd commented on inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
> +        return (int)url_to_postid($url);
It looks like method calls itself. Infinite recursion?

2021-09-14 23:29 UTC, dimitrystd commented on tests/IntegrationTests/tests/AttachmentsTest.php
> +class AttachmentsTest extends SmartlingUnitTestCaseAbstract
Class name doesn't correlate with test name. Do we really rewrite external links as part of attachments handling?

2021-09-14 23:30 UTC, dimitrystd requested changes
Let's talk about how it may help client

2021-09-15 07:28 UTC, PavelLoparev commented on inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
> +        return (int)url_to_postid($url);
I believe it was infinite recursion but now it's just wrapper (for tests purposes?) for `url_to_postid` wp function.

2021-09-15 07:29 UTC, PavelLoparev approved these changes

2021-09-15 08:46 UTC, vsolovei-smartling commented on tests/IntegrationTests/tests/AttachmentsTest.php
> +class AttachmentsTest extends SmartlingUnitTestCaseAbstract
We rewrite links to post based content

2021-09-15 08:46 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
> +        return (int)url_to_postid($url);
Yes

2021-09-15 08:47 UTC, vsolovei-smartling commented
> Let's talk about how it may help client

Without this, code ends up in infinite recursion. Some php configurations are able to catch this condition, most are not.

2021-09-15 17:20 UTC, dimitrystd approved these changes

2021-09-15 18:13 UTC, merged