use distributed lock service instead of DB locking (WP-643)
Smartling/wordpress-localization-plugin pull request #320
Opened 2021-09-22 16:23 UTC by vsolovei-smartling

2021-09-23 12:55 UTC, dimitrystd requested changes

2021-09-23 12:55 UTC, dimitrystd commented on inc/Smartling/Jobs/JobAbstract.php
>          return 'smartling_cron_flag_' . $this->getJobHookName();
Let's use `wordpress_smartling_cron_flag_` because we use global storage now

2021-09-23 12:55 UTC, dimitrystd commented on inc/Smartling/Jobs/JobAbstract.php
> +        if ($renew) {
Let's remove `$renew` parameter because we can't use it by design

2021-09-23 13:09 UTC, PavelLoparev requested changes

2021-09-23 13:09 UTC, PavelLoparev commented on inc/Smartling/Jobs/JobAbstract.php
> +            return;
Don't we need to throw an exception here? What happens in client's code that calls `placeLockFlag` with no active profile? Will it still try to run some job?

2021-09-23 13:09 UTC, PavelLoparev commented on inc/Smartling/Jobs/JobAbstract.php
> +        }
Same here. Also, seems like it's code duplication. Does it make sense to extract to somethink like `getActiveProfile()`?

2021-09-23 13:09 UTC, PavelLoparev commented on inc/Smartling/Jobs/JobAbstract.php
> +            $this->placeLockFlag();
So, yep, if there is no active profile you will try to still run this job and something will fail.

2021-09-23 13:09 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
> +                do_action(DownloadTranslationJob::JOB_HOOK_NAME);
Didn't get this change

2021-09-23 13:11 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/LoggerSafeTrait.php
> -    private LoggerInterface $logger;
Prevents "Typed property ... must not be accessed before initialization" errors

2021-09-23 13:11 UTC, vsolovei-smartling commented on inc/config/cron.yml
> +  cron.job.default_ttl: 60
With proper locking there is no need to hold the locks for 20 minutes.

2021-09-23 13:19 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
> +                do_action(DownloadTranslationJob::JOB_HOOK_NAME);
With distributed locking, we no longer can provide the user with ttl left until expiry

2021-09-23 13:25 UTC, PavelLoparev commented on inc/Smartling/Helpers/LoggerSafeTrait.php
> -    private LoggerInterface $logger;
Wow, that does sound like a bug in PHP's traits

2021-09-23 13:27 UTC, PavelLoparev commented on inc/Smartling/Jobs/DownloadTranslationJob.php
> +        parent::__construct($api, $settingsManager, $submissionManager, $jobRunInterval, $workerTTL);
No action points to current PR though

2021-09-23 16:58 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +        if ($renew) {
It is used appropriately

2021-09-23 17:06 UTC, vsolovei-smartling commented on inc/config/cron.yml
> +  cron.job.default_ttl: 60
Discussed with @dimitrystd, changed to 180. Should reduce it further after removing automatic relations handling.

2021-09-23 17:07 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
>          return 'smartling_cron_flag_' . $this->getJobHookName();
Done

2021-09-23 17:10 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +            return;
Thanks, good catch, will now throw exception

2021-09-23 17:11 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/DownloadTranslationJob.php
> +        parent::__construct($api, $settingsManager, $submissionManager, $jobRunInterval, $workerTTL);
Sorry about that, my only defence is we never want/have time to refactor something. I will go with independent PRs approach in the future.

2021-09-23 17:11 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +        }
Done

2021-09-23 17:11 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +            $this->placeLockFlag();
Fixed

2021-09-23 17:25 UTC, dimitrystd requested changes

2021-09-23 17:25 UTC, dimitrystd commented on inc/Smartling/Jobs/JobAbstract.php
> +            return;
Good point, we should interrupt job execution. It's similar to the case when we can't acquire the lock.

2021-09-23 17:25 UTC, dimitrystd commented on inc/Smartling/Jobs/JobAbstract.php
> +        } catch (SmartlingApiException $e) {
I think we must catch all exceptions here because it's one of plugin "entry point". So ideal structure can be
```php
private function tryRunJob(): void
{
  try {
    $this->placeLockFlag();
    try {
      $this->run();
    // } catch (...) {...} You can add it only if you would like to handle specific exception of add more data into exception
    } finally {
      $this->dropLockFlag();
    }
  } catch (\Exception $exception) {
    // We log ALL exceptions here
  }
}
```

2021-09-24 12:16 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
> +                do_action(DownloadTranslationJob::JOB_HOOK_NAME);
I gave it a second thought, and a message saying we're unable to acquire lock is better than nothing, reverted

2021-09-24 12:16 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +        } catch (SmartlingApiException $e) {
Done

2021-09-24 12:37 UTC, dimitrystd approved these changes

2021-09-24 12:37 UTC, dimitrystd commented on readme.txt
> +* Switched from database to external service locking for cron jobs
Let's add details for the history. 
```
. It avoids the issue when hosting doesn't allow SQL `SELECT ... FOR UPDATE`
```

2021-09-24 18:16 UTC, dimitrystd approved these changes

2021-09-27 09:04 UTC, PavelLoparev approved these changes

2021-09-27 10:58 UTC, merged