add deleted submission status (WP-659)
Smartling/wordpress-localization-plugin pull request #334
Opened 2021-10-27 14:04 UTC by vsolovei-smartling

WIP, delete status that matches other connectors

2021-11-02 19:57 UTC, dimitrystd requested changes

2021-11-02 19:57 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionManager.php
> +    public function getEntityById(int $id): ?SubmissionEntity
To be honest, it confuses that request by **Id** will not return deleted submission. As for me, it's a single way to get raw data from DB. Or let's never return deleted and get rid of comment in the method above `Deleted submissions ARE NOT excluded`
Same story for `findByIds()`

2021-11-02 19:57 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionManager.php
> +        $block->addCondition(Condition::getCondition(ConditionBuilder::CONDITION_SIGN_NOT_EQ, SubmissionEntity::FIELD_STATUS, [SubmissionEntity::SUBMISSION_STATUS_DELETED]));
You made a major change in behavior but non of unit-tests failed. Let's add unit-tests to lock the new behavior (never return DELETED submissions)

2023-11-23 16:36 UTC, vsolovei-smartling commented
Stale

2023-11-23 16:36 UTC, closed without merging