add test run frontend (WP-662)
Smartling/wordpress-localization-plugin pull request #345
Opened 2021-11-24 14:12 UTC by vsolovei-smartling

New section
![image](https://user-images.githubusercontent.com/60617669/143254740-7f2e5a52-9d7c-473d-9636-74f5c0337c41.png)
Backend basis for test run included, will need to act on results in a future PR

2021-11-24 15:19 UTC, PavelLoparev requested changes

2021-11-24 15:19 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        }
So, you've already refactored `BaseAjaxServiceAbstract` constructor to receive request data. Why do you need to pass the same here once again? Why don't we pass needed parameters to `$_GET` from UI?

2021-11-24 15:29 UTC, PavelLoparev requested changes

2021-11-24 15:29 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/TestRunController.php
> +                'targetBlogIds' => $targetBlogId,
Shouldn't it be `[$targetBlogId]`?

2021-11-24 15:31 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        }
Oh, because it's used only for logging and this method is also called from the loop with different params. Ok, but looks strange anyway

2021-11-24 15:37 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        }
Actually no, it's not ok) The problem is that `ContentRelationsDiscoveryService` class mixes inside the controller and service layer. And `actionHandler` method is a controller that returns json response. And the problem is that you are trying to use this controller as a service to get relations. I think we need to separate the service layer, inject it to the `ContentRelationsDiscoveryService` and use it there. And leave this class (do not modify its returning value depending on `$data === null`). What you should do is that use that new service layer class in you `testRun` method instead of calling `ContentRelationsDiscoveryService::actionHandler`

2021-11-29 12:06 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/TestRunController.php
> +                'targetBlogIds' => $targetBlogId,
No, it's passed from frontend and expects a comma-delimited string

2021-11-29 12:07 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        }
Done

2021-11-29 15:58 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/TestRunController.php
> +                'targetBlogIds' => $targetBlogId,
got it

2021-12-16 07:42 UTC, merged