add test run backend (WP-668)
Smartling/wordpress-localization-plugin pull request #350
Opened 2021-12-13 12:35 UTC by vsolovei-smartling

2021-12-13 17:04 UTC, PavelLoparev requested changes

2021-12-13 17:04 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsHandler.php
> +            $this->returnSuccess(['data' => $this->service->getRelations($data['content-type'], (int)$data['id'], $data['targetBlogIds'])->toArray()]);
In previous line of code we did not call `toArray()`.

2021-12-13 17:04 UTC, PavelLoparev commented on inc/Smartling/Settings/SettingsManager.php
> +            return $profile->getTargetLocales()[0]->getSmartlingLocale();
Is it possible to run test before setting up target locales (so that [0] is unset yet)?

2021-12-14 14:17 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +        }
No, it is not stored anywhere

2021-12-14 14:18 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/TestRunHelper.php
> +        return $id === (int)SimpleStorageHelper::get(TestRunController::TEST_RUN_BLOG_ID_SETTING_NAME);
Done

2021-12-14 14:19 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/TestRunHelper.php
> +    }
The `return`s seen are in closures, method always returns void

2021-12-14 14:20 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +            SimpleStorageHelper::set($this->getJobHookName() . self::LAST_FINISH_SUFFIX, time());
An improvement, will display a warning at the test run page, if last cron finish time was too long ago

2021-12-14 14:21 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsHandler.php
> +            $this->returnSuccess(['data' => $this->service->getRelations($data['content-type'], (int)$data['id'], $data['targetBlogIds'])->toArray()]);
DetectedRelations was extracted in order to prevent looking up array keys. Previous line worked with an array, changed line works with class, but returnSuccess data is expected to be array

2021-12-14 14:23 UTC, vsolovei-smartling commented on inc/Smartling/Settings/SettingsManager.php
> +            return $profile->getTargetLocales()[0]->getSmartlingLocale();
Done

2021-12-14 14:24 UTC, vsolovei-smartling commented on inc/Smartling/WP/View/TestRun.php
> +    echo '<p>You need to either <a href="' . get_admin_url(null, '/network/site-new.php') . '">add a new site</a> or completely remove submissions from an existing one to start a test run.</p>';
Not yet we don't

2021-12-14 15:06 UTC, PavelLoparev commented on inc/Smartling/Helpers/TestRunHelper.php
> +    }
Oh, my bad.

2021-12-14 15:09 UTC, PavelLoparev approved these changes

2021-12-16 07:42 UTC, merged