fix sending if no related content present (WP-685)
Smartling/wordpress-localization-plugin pull request #359
Opened 2022-01-26 10:38 UTC by vsolovei-smartling

visibility PR, issue discovered while manually testing 2.11.2 after its release

2022-01-26 13:47 UTC, PavelLoparev approved these changes

2022-01-26 19:52 UTC, dimitrystd requested changes

2022-01-26 19:52 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsHandler.php
> +    public function createSubmissionsHandler(array $data = null): void
Optional parameter triggered me.
As far as I understand this function is called from our JS function. Can we do this magic `$data = $_POST;` on browser side and always expect input data in the same format?

2022-01-27 06:36 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsHandler.php
> +    public function createSubmissionsHandler(array $data = null): void
No, we can't do that, php doesn't allow expressions as default values. The function will always be called without a parameter in production, this change was made for testing.

2022-01-28 09:28 UTC, merged