add audit logs
Smartling/wordpress-localization-plugin pull request #372
Opened 2022-04-18 12:43 UTC by vsolovei-smartling

2022-04-18 15:13 UTC, PavelLoparev requested changes

2022-04-18 15:13 UTC, PavelLoparev commented on inc/Smartling/ApiWrapperWithRetries.php
> +    }
Can this be implemented as a magic method call instead of copypasting this wrapper `withRetry` call for every new method in the class? No action points, just thinking

2022-04-18 15:13 UTC, PavelLoparev commented on inc/Smartling/ApiWrapper.php
> +        $record = new CreateRecordParameters();
Let's add some more data:

Client fields (should simplify user identification):
- setClientUserEmail
- setClientUserName

Env info fields:
- setEnvId

Client data fields:
- setClientData (should we log any wp related data to the event like submission id/submission created/etc)

2022-04-18 15:14 UTC, PavelLoparev reviewed
lgtm. left some comments

2022-04-18 15:20 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +    }
This log states `due to user request` but is `storeWithJobInfo` always being called due to user request? I mean daily job for instance. I think this log should be moved outside this `logSubmissionCreated` method and put right before creating log record. And then there will be no sense in `logSubmissionCreated` at all

2022-04-18 15:28 UTC, PavelLoparev commented on inc/Smartling/ApiWrapperWithRetries.php
> +    }
Actually, I think this class can contain only one magic method and look like this:
```
class ApiWrapperWithRetries implements ApiWrapperInterface {
    ...

    public function __construct(ApiWrapperInterface $base)
    {
        $this->base = $base;
    }

    __call($name, $parameters) {
        $this->withRetry(function () use ($name, $parameters) {
            all_user_func_array(array($this->base, $methodName), $parameters);
        });
    }
}
```

2022-04-19 11:26 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapperWithRetries.php
> +    }
It could, but we have methods that need no retrying, and it would still have to implement the methods in the interface. I know this looks strange, but we don't often modify ApiWrapper methods

2022-04-19 11:26 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +        $record = new CreateRecordParameters();
@dimitrystd, we discussed GDPR requirements, do you know whom could I contact to clarify whether we could use the name and email?

2022-04-19 11:28 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +    }
At the moment, yes, the basis for the function call depends on a recently introduced TranslationRequest class, that is intended for frontend requests.

2022-04-19 14:36 UTC, dimitrystd requested changes

2022-04-19 14:36 UTC, dimitrystd commented on inc/Smartling/ApiWrapper.php
> +    public function auditLogCreate(SubmissionEntity $submission, string $actionType, string $description, ?bool $isAuthorize = null): void
Agree, other methods also start with verb.

2022-04-19 14:36 UTC, dimitrystd commented on inc/Smartling/ApiWrapper.php
> +        $record = new CreateRecordParameters();
>GDPR requirements

Yep, it appeared last week. I'm going to raise this question with Max and Evgeniy. Then, depending on discussions results, talk to AlexS.
But let's don't wait for decision and move on with user_id so far. We can add the real name later.

>setClientData (should we log any wp related data to the event like submission id/submission created/etc?)

Totally agree. Let's add IDs (page, source\target blogs, submission id)

2022-04-19 14:36 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        $this->getLogger()->info(sprintf("Adding submissionId=%d, fileName=%s, sourceBlogId=%d, sourceId=%d for upload to batchUid=%s due to user request, reason=\"%s\"", $submission->getId(), $submi
As for me, this log looks redundant. I think we should log once in `bulkUpload()` (before the loop).

2022-04-19 14:36 UTC, dimitrystd commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +                $this->logSubmissionCreated($submission, 'Bulk upload request', false);
I just realized that it will be 1 log entry per post and locale. It will be too much. We do similar for PP, but I'm not sure that we need it from the beginning here.
I thought about a single audit record for each user request. Very similar to what we send in ajax payload from UI (job, current post, auto-authorize; related items; etc).

2022-04-19 14:50 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +                $this->logSubmissionCreated($submission, 'Bulk upload request', false);
Ok, will change accordingly

2022-04-20 10:45 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +    public function auditLogCreate(SubmissionEntity $submission, string $actionType, string $description, ?bool $isAuthorize = null): void
Done

2022-04-20 10:45 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +        $record = new CreateRecordParameters();
Done

2022-04-20 10:45 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        $this->getLogger()->info(sprintf("Adding submissionId=%d, fileName=%s, sourceBlogId=%d, sourceId=%d for upload to batchUid=%s due to user request, reason=\"%s\"", $submission->getId(), $submi
Done

2022-04-20 10:45 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +                $this->logSubmissionCreated($submission, 'Bulk upload request', false);
Done

2022-04-20 10:46 UTC, vsolovei-smartling commented
I've also renamed CloneRequest and TranslationRequest to UserCloneRequest and UserTranslationRequest to clarify their intended use

2022-04-20 10:49 UTC, vsolovei-smartling commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        $this->getLogger()->info(sprintf("Adding submissionId=%d, fileName=%s, sourceBlogId=%d, sourceId=%d for upload to batchUid=%s due to user request, reason=\"%s\"", $submission->getId(), $submi
I've extracted the audit log creation, but think no harm in having detailed submission creation logs

2022-04-20 14:23 UTC, PavelLoparev approved these changes

2022-04-20 14:23 UTC, PavelLoparev commented on inc/Smartling/WP/Table/SubmissionTableWidget.php
> +                            ];
Code duplications. Seems like could be extracted to some method

2022-04-20 14:23 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        ], $jobInfo, $job->isAuthorize());
@dimitrystd https://bt.smartling.net/browse/ALS-43

2022-04-20 16:18 UTC, PavelLoparev commented on inc/Smartling/Services/ContentRelationsDiscoveryService.php
> +        ], $jobInfo, $job->isAuthorize());
@vsolovei-smartling could you please validate in field types described in the ticket above?

2022-04-20 18:48 UTC, vsolovei-smartling commented on inc/Smartling/WP/Table/SubmissionTableWidget.php
> +                            ];
These are two different data sets with two different sources, added a comment in [bt](https://bt.smartling.net/browse/ALS-43)

2022-04-20 20:40 UTC, dimitrystd approved these changes

2022-04-28 08:50 UTC, merged