add retries for batch not suitable (WP-807)
Smartling/wordpress-localization-plugin pull request #461
Opened 2023-06-14 11:51 UTC by vsolovei-smartling

2023-06-14 11:52 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapperInterface.php
> -        /** @noinspection PhpLanguageLevelInspection */
Minimum version is php 8, this is redundant

2023-06-14 14:51 UTC, dimitrystd requested changes

2023-06-14 14:51 UTC, dimitrystd commented on inc/Smartling/ApiWrapper.php
> +    public function findJobByBatchUid(ConfigurationProfileEntity $profile, string $batchUid): ?JobEntityWithStatus
Jobs API doesn't know about batches. I don't understand how it can work.

2023-06-14 15:32 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +    public function findJobByBatchUid(ConfigurationProfileEntity $profile, string $batchUid): ?JobEntityWithStatus
I've misread the parameters, you are correct. Fixed.

2023-06-14 15:37 UTC, dimitrystd requested changes

2023-06-14 15:37 UTC, dimitrystd commented on inc/Smartling/ApiWrapper.php
> +        $result = $this->getJobsApi($profile)->searchJobs($parameters);
We know that the same file can be uploaded many times. Please sort jobs by time Desc.

2023-06-15 10:04 UTC, vsolovei-smartling commented on inc/Smartling/ApiWrapper.php
> +        $result = $this->getJobsApi($profile)->searchJobs($parameters);
Done

2023-06-15 18:49 UTC, dimitrystd approved these changes

2023-06-15 18:49 UTC, dimitrystd commented on inc/Smartling/ApiWrapper.php
> +        $result = array_reduce($this->getJobsApi($profile)->searchJobs($parameters), static function (?array $carry, array $item): array {
OMG, how complex the `sort` + `first` implementations look in php.

2023-06-19 09:17 UTC, merged