add microseconds to log output (WP-822)
Smartling/wordpress-localization-plugin pull request #478
Opened 2023-08-11 09:51 UTC by vsolovei-smartling

Resulting log lines start with [2023-08-11 09:49:25.641179]

2023-08-11 11:55 UTC, dimitrystd requested changes

2023-08-11 11:55 UTC, dimitrystd commented on inc/config/logger.yml
> -  logger.formatter.date: "Y-m-d H:i:s"
Recommended format "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

2023-08-11 13:50 UTC, vsolovei-smartling commented on inc/config/logger.yml
> -  logger.formatter.date: "Y-m-d H:i:s"
Now is [2023-08-11T13:49:24.079624Z]

2023-08-11 15:11 UTC, PavelLoparev approved these changes

2023-08-11 15:11 UTC, PavelLoparev commented on inc/config/logger.yml
> -  logger.formatter.date: "Y-m-d H:i:s"
Let's make sure Splunk correctly handles microseconds as well. lgtm

2023-08-11 15:45 UTC, vsolovei-smartling commented on inc/Smartling/DITrait.php
> +            ->addArgument($di->getParameter('logger.formatter.date'));
Is there a reason not to move this to .yml entirely?

2023-08-11 15:45 UTC, vsolovei-smartling commented on inc/config/logger.yml
> -  logger.formatter.date: "Y-m-d H:i:s"
Ok, some code changes are required
<img width="349" alt="image" src="https://github.com/Smartling/wordpress-localization-plugin/assets/60617669/f190fb7d-4ebd-40a5-b595-5e9b75f7be1d">

2023-08-11 20:52 UTC, dimitrystd approved these changes

2023-08-11 20:52 UTC, dimitrystd commented on inc/Smartling/DITrait.php
> +            ->addArgument($di->getParameter('logger.formatter.date'));
I don't know why. Probably because there are other logger variables `logger.formatter.*`. We can keep it there.

2023-08-11 20:52 UTC, dimitrystd commented on inc/config/logger.yml
> -  logger.formatter.date: "Y-m-d H:i:s"
`u` - microseconds also should work, sitecore sends in this format. Can you pls check how it works in kibana? it must parse it, otherwise you will not see your logs.
`v` - milliseconds looks more common.

2023-08-14 08:09 UTC, PavelLoparev approved these changes

2023-08-15 09:48 UTC, vsolovei-smartling commented
The kibana time stores only milliseconds, but I don't think we should rebuild the index to include microseconds. I've also refactored the code to be in the config, instead of DITrait

2023-08-15 10:53 UTC, vsolovei-smartling commented on inc/config/logger.yml
> +        - "@fileLoggerHandlerRotatable"
This is a nested array, the third parameter in LevelLogger expects an array, and we provide an array of one CustomRotatingFileHandler

2023-08-15 10:58 UTC, PavelLoparev approved these changes

2023-08-15 19:11 UTC, dimitrystd approved these changes

2023-08-16 08:34 UTC, merged