switch to new formula (WP-833)
Smartling/wordpress-localization-plugin pull request #487
Opened 2023-09-29 12:41 UTC by vsolovei-smartling

2023-09-29 14:36 UTC, PavelLoparev approved these changes
Please add more test cases as described [here](https://bt.smartling.net/browse/CFUL-589?focusedCommentId=174437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-174437).

2023-09-29 14:48 UTC, dimitrystd requested changes

2023-09-29 14:48 UTC, dimitrystd commented on inc/Smartling/Submissions/SubmissionEntity.php
> +        return (int)round(($this->getCompletedStringCount() / $translatableCount) * 100);
You must use `floor`, wiki contains details about it.

2023-09-29 14:48 UTC, dimitrystd commented on tests/Smartling/Submissions/SubmissionEntityTest.php
> +    public function completionPercentageDataProvider(): array
The last sentence of the [wiki page](https://wiki.smartling.net/pages/viewpage.action?pageId=34209978) includes links to the tests. Can you use the same set of test results? For example, your test didn't catch the bug with `round`.

2023-10-02 20:10 UTC, dimitrystd commented on readme.txt
> +* Fixed connector automatically downloading content and applying translation after source was uploaded again with no new authorized strings. The connector now will automatically download submissions
Your explanation is correct, but I decided to add specifics about what happened and how it will work now.
```suggestion
* Fixed a use case in which an already translated post was re-uploaded, new source strings were not authorized, and the connector re-delivered translations. It happened because all authorized strings are published. This type of re-delivery confused people because it was unexpected, but it also included new strings that were untranslated.
Starting with this release, delivery will occur when all authorized strings have been translated and published. Any unauthorized string will prevent the delivery. To unblock delivery, any unauthorized strings should be Excluded or Authorized.
```

2023-10-03 10:06 UTC, vsolovei-smartling commented on readme.txt
> +* Fixed connector automatically downloading content and applying translation after source was uploaded again with no new authorized strings. The connector now will automatically download submissions
Thanks!

2023-10-03 11:12 UTC, merged