add impersonation (WP-865)
Smartling/wordpress-localization-plugin pull request #508
Opened 2024-01-26 12:25 UTC by vsolovei-smartling

The issue was with Elementor checking the permissions, and cron user has no permissions

2024-01-26 12:43 UTC, vsolovei-smartling commented
Verified on their staging

2024-01-26 16:16 UTC, PavelLoparev requested changes

2024-01-26 16:16 UTC, PavelLoparev commented on composer.json
> +  "version": "3.8.6",
Sounds like this is new non bc feature rather than bug fix. Shouldn't it be `3.9.0` instead?

2024-01-26 16:16 UTC, PavelLoparev commented on inc/Smartling/Base/ExportedAPI.php
> +    public const ACTION_AFTER_TARGET_METADATA_WRITTEN = 'smartling_action_after_target_content_written';
Value is the same as in `ACTION_AFTER_TARGET_CONTENT_WRITTEN` constant.

2024-01-26 16:16 UTC, PavelLoparev commented on inc/Smartling/Helpers/UserHelper.php
> +        }
Maybe throw here? Sounds like for the client's code it's not expected to proceed with non privileged user in `asAdministratorOrEditor` .

2024-01-26 16:44 UTC, vsolovei-smartling commented on inc/Smartling/Base/ExportedAPI.php
> +    public const ACTION_AFTER_TARGET_METADATA_WRITTEN = 'smartling_action_after_target_content_written';
Thanks, fixed!

2024-01-26 16:44 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/UserHelper.php
> +        }
I had my doubts here, no huge difference for now, will throw

2024-01-26 17:11 UTC, PavelLoparev commented on inc/Smartling/Helpers/UserHelper.php
> +        }
I mean, if it doesn't throw then probably client will face the same issue as before, right? I don't insist on throwing, just trying think outloud.

2024-01-26 17:11 UTC, PavelLoparev approved these changes

2024-01-26 17:14 UTC, PavelLoparev commented on inc/Smartling/Helpers/UserHelper.php
> +            throw new SmartlingHumanReadableException('Unable to get administrator or editor to process content in blog ' . $this->wp->get_current_blog_id(), 'no.privileged.user', 403);
Oh, we have a similar approach in SUBM (and I'm not proud of that) where the business logic layer throws infrastructure layer exceptions (403 etc). Probably not part of this PR, but somewhen we would need to reconsider error handling. The service layer must throw service exceptions and the error handler on the infrastructure level must map those service layer exceptions to something other.

2024-01-29 12:06 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/UserHelper.php
> +        }
Yes, it's better to throw instead of trying to continue as user without permissions, logs will be clearer

2024-01-29 12:06 UTC, vsolovei-smartling commented on inc/Smartling/Helpers/UserHelper.php
> +            throw new SmartlingHumanReadableException('Unable to get administrator or editor to process content in blog ' . $this->wp->get_current_blog_id(), 'no.privileged.user', 403);
Introduced new exception

2024-01-29 12:06 UTC, merged

2024-01-29 18:31 UTC, dimitrystd reviewed
I believe you had a text file where you noted all major changes in "API". Just wanted to remind and confirm that we don't need it anymore since no 3rd party developers use our integration.