add support for redirection plugin (WP-869)
Smartling/wordpress-localization-plugin pull request #510
Opened 2024-01-31 13:27 UTC by vsolovei-smartling

alternative to #509

2024-02-01 11:11 UTC, PavelLoparev requested changes

2024-02-01 11:11 UTC, PavelLoparev commented on inc/Smartling/Jobs/JobAbstract.php
> +    private function tryRunJob(string $source = ''): void
What values can be in this string? `user` and what else?

2024-02-01 11:11 UTC, PavelLoparev commented on inc/Smartling/WP/Controller/ConfigurationProfilesController.php
> +        $link = $this->linkHelper->getRedirected('https://localhost.localdomain/test');
Looks like debug leftover?

2024-02-01 11:45 UTC, vsolovei-smartling commented on inc/Smartling/Jobs/JobAbstract.php
> +    private function tryRunJob(string $source = ''): void
It can only be user, the idea is to not throttle the requests from front end explicitly called by user

2024-02-01 11:46 UTC, vsolovei-smartling commented on inc/Smartling/WP/Controller/ConfigurationProfilesController.php
> +        $link = $this->linkHelper->getRedirected('https://localhost.localdomain/test');
Yes, removed

2024-02-01 11:51 UTC, PavelLoparev approved these changes

2024-02-01 11:52 UTC, PavelLoparev commented
But I also don't get which approach should be used. This PR or https://github.com/Smartling/wordpress-localization-plugin/pull/509.

2024-02-02 14:21 UTC, vsolovei-smartling commented on inc/Smartling/WP/Table/BulkSubmitTableWidget.php
> +    public function processBulkAction(): void
For reason unknown to me, changing Elementor integration test causes two unrelated tests to fail with `unable to redeclare function`. I've made the tests less brittle, minor changes, test related

2024-02-02 14:21 UTC, vsolovei-smartling commented on tests/Smartling/WP/Table/BulkSubmitTableWidgetTest.php
> +            $x = new class($this->createMock(LocalizationPluginProxyInterface::class), $this->createMock(SiteHelper::class), $core, $manager, $profile) extends BulkSubmitTableWidget {
Avoid calling WordPress underlying constructor

2024-02-02 16:25 UTC, vsolovei-smartling commented
Had some architectural changes, discussed with @dimitrystd yesterday

2024-02-02 18:03 UTC, dimitrystd approved these changes

2024-02-03 11:29 UTC, PavelLoparev approved these changes

2024-02-05 12:39 UTC, merged