add upload queue (WP-881)
Smartling/wordpress-localization-plugin pull request #525
Opened 2024-04-08 12:00 UTC by vsolovei-smartling

2024-04-10 08:02 UTC, PavelLoparev reviewed
I'm confused, I thought switching to batch api v2 it's only about introducing new sdk dependency + rewriting upload queue handler/worker. Why are there so many changes to core code (massive refactoring of core trait, upload flow etc)?

2024-04-11 09:12 UTC, vsolovei-smartling commented
> I'm confused, I thought switching to batch api v2 it's only about introducing new sdk dependency + rewriting upload queue handler/worker. Why are there so many changes to core code (massive refactoring of core trait, upload flow etc)?

The previous implementation relied on jobUids, vs batchUids for the submission upload queue in this one. I've reverted changes to `JobEntityWithBatchUid` but had to include the required changes from the previous implementation, as trying to merge into previous implementation produces a bigger changeset

2024-04-11 09:53 UTC, PavelLoparev approved these changes

2024-04-11 21:36 UTC, dimitrystd requested changes
Left only one comment about DB table. I think it's the most important part of this refactoring. The queue describes the command for post/taxonomy. But each post is represented by one or many submissions + batchUid.

2024-04-11 21:36 UTC, dimitrystd commented on inc/Smartling/Models/UploadQueueEntity.php
> +            self::FIELD_SUBMISSION_ID => SmartlingEntityAbstract::DB_TYPE_U_BIGINT,
This DB record should contain one "command" - upload postX to 5 locales. Since each locale is represented by its own submission, then the table must reflect it. One db record must contain an array of submission ids.

2024-04-12 18:06 UTC, vsolovei-smartling commented on inc/Smartling/Models/UploadQueueEntity.php
> +            self::FIELD_SUBMISSION_ID => SmartlingEntityAbstract::DB_TYPE_U_BIGINT,
Done

2024-04-15 11:19 UTC, merged