add import flow (WP-826)
Smartling/wordpress-localization-plugin pull request #526
Opened 2024-04-22 12:02 UTC by vsolovei-smartling

2024-04-25 09:57 UTC, PavelLoparev requested changes

2024-04-25 09:57 UTC, PavelLoparev commented on inc/Smartling/ContentProvider.php
> +            'parent_id' => $assetUid->getId(),
`$assetUid->getId()`, let's stick to uid (`getUid()`) naming?

2024-04-25 09:57 UTC, PavelLoparev commented on inc/Smartling/RestApi.php
> +                    }
What does this mean? Response should be only given by corresponding method from `$this->getProvider()` object, why `$assetUid` can already be an instance of `WP_REST_Response`? And also, this code is repeated in every controller, maybe extract it to some method?

2024-04-25 09:57 UTC, PavelLoparev commented on inc/Smartling/RestApi.php
> +                        ($parsed['related']['include'] ?? false) ? $parsed['related']['depth'] ?? 0 : 0,
Let's introduce validation for incoming parameters? For now it seems like there is no validation rules for input at all? `$parsed` can be anything

2024-04-25 09:57 UTC, PavelLoparev commented on inc/Smartling/RestApi.php
> +            return new \WP_REST_Response($e->getMessage(), 400);
It's strange that business logic code returns infrastructure level objects (getAssetUid returns data or returns http response). I think returning http response should be implemented in place where this method is called.

2024-04-26 08:26 UTC, vsolovei-smartling commented on inc/Smartling/ContentProvider.php
> +            'parent_id' => $assetUid->getId(),
This is WP content id, don't think `getUid()` naming reflects this

2024-04-26 08:26 UTC, vsolovei-smartling commented on inc/Smartling/RestApi.php
> +                    }
Refactored

2024-04-26 08:26 UTC, vsolovei-smartling commented on inc/Smartling/RestApi.php
> +                        ($parsed['related']['include'] ?? false) ? $parsed['related']['depth'] ?? 0 : 0,
Done

2024-04-26 08:26 UTC, vsolovei-smartling commented on inc/Smartling/RestApi.php
> +            return new \WP_REST_Response($e->getMessage(), 400);
Refactored

2024-05-07 08:08 UTC, PavelLoparev approved these changes

2024-05-07 11:47 UTC, merged